apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cpq8wdkri-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cpq8wdkri-java-springboot-gitops